MapEditor/RagnarockMap.cs

(untested, but it seems like a simple thing to fix)
As of the current update, you have to manually edit the difficulty value in info.dat if you want to go above 10. This change *should* allow maps with modified info.dat difficulties to load unless I'm being stupid about it.

Possible way to fix part of the difficulty lock

---

Windows/MainWindow.UIControls.cs

Fixed an issue with old song title still appearing in Recently Opened after it's been changed in the editor and saved.
Steps to reproduce on v1.1.0:
1. Open Edda.
2. Select "New Map".
3. Select folder and song file.
4. Change the Song Name in the editor and save.
5. Close Edda and open it again.
Expected outcome: the new map is visible at the top of Recently Opened with the new Song Name.
Actual outcome: the new map is visible at the top of Recently Opened as "Untitled Map".

Recently Opened doesn't show updated song name

---

Windows/DifficultyPredictorWindow.xaml.cs

Fixed an issue where app would crash when predicting difficulty if user had locale where ',' is the decimal separator instead of '.'

Difficulty prediction crashes the application

---

Classes/Helper.cs
Windows/MainWindow.UIControls.cs
Windows/MainWindow.xaml
Windows/MainWindow.xaml.cs

https://github.com/PKBeam/Edda/issues/29
Improvements in UX for several text boxes where user might expect feedback on clicking Enter.
Implemented new keyboard shortcut Ctrl+MouseWheel to make changing Beat Division on the fly more convenient. Scrolling updates the textbox, but the line re-rendering only happens when Ctrl is released for performance reasons.
**Note:** after this change, while Ctrl is pressed, scrolling on the grid is disabled. This might not be apparent to the user at first glance.

Improvements in UX when changing Beat Division

---

Classes/EddaConstants.cs
Classes/Helper.cs
Classes/MapConverters/StepManiaMapConverter.cs
Windows/MainWindow.xaml.cs

#31 
Added support for JFIF cover images. Changed the behavior for selected cover images - they're copied over to the map folder as cover.(jpg|jpeg|jfif) instead of their actual filename.

Selected cover image should be renamed to cover.jpg when copied to map directory

---

Classes/Audio/DeviceChangeListener.cs
Classes/Audio/ParallelAudioPlayer.cs
Classes/EddaConstants.cs
Windows/MainWindow.UIControls.cs
Windows/MainWindow.xaml.cs
Windows/SettingsWindow.xaml
Windows/SettingsWindow.xaml.cs

#32 
Implemented support for selecting preferred output device. 
Edda will also now listen for changes to devices in system and will adjust its output device accordingly.

Allow changing audio output device in Edda

---

Classes/MapEditor/MapEditor.cs
Windows/ChangeBPMWindow.xaml
Windows/ChangeBPMWindow.xaml.cs
Windows/MainWindow.UIControls.cs
Windows/MainWindow.xaml.cs

This is to avoid asking user to save when closing the map without any changes.
Separate tracking for info.dat and each difficulty map is implemented due to some actions having partial saving only on info.dat, but not on the difficulty maps.
I've had to add some initialization logic in MainWindow to avoid marking the map as "dirty" when map is first opened or difficulty is changed and the UI elements have their values programatically changed, as this resulted in poor user experience.

#26 Implemented tracking for unsaved changes in the map editor 

---

Classes/Audio/VorbisSpectrogramGenerator.cs
Classes/UI/EditorGridController.cs
Windows/ChangeBPMWindow.xaml.cs
Windows/MainWindow.GridControls.cs
Windows/MainWindow.UIControls.cs
Windows/MainWindow.xaml
Windows/MainWindow.xaml.cs

I was investigating an issue with unintended notes being placed if you double-click the map you want to open and found some more issues that sometimes occur when clicking on elements that haven't been loaded in yet.
In particular, clicking on waveform/spectrogram while the map re-loads forces a re-draw from a different thread, which caused issues with some objects being still in disposed state from previously closing the map.

Fixed a few issues occuring when clicking during window initialization

---

Classes/Audio/VorbisSpectrogramGenerator.cs
Classes/EddaConstants.cs
Classes/UI/EditorGridController.cs
Windows/MainWindow.GridControls.cs
Windows/MainWindow.MenuItems.cs
Windows/MainWindow.UIControls.cs
Windows/MainWindow.xaml
Windows/MainWindow.xaml.cs
Windows/SettingsWindow.xaml
Windows/SettingsWindow.xaml.cs

#24
Added a way to resize the column with spectrogram to get both a better look at the image and to allow users to drag it closer to the note editor to check their alignment.
Added caching for spectrogram to make sure we don't re-do expensive calculations unnecessarily when opening a map again or resizing the spectrogram.
Added user settings for customizing the spectrogram, including algorithm used, frequency range and colormap (previously it was always MelScale, 16kHZ, Blues). I've set the defaults to Standard, 11kHz, which seems about the same settings that are used by MMA2 for their spectrogram. I've left Blues as the default colormap for theming, but after testing a few I actually found I prefer Lopora more and I saw that MMA2 uses Plasma.
White bar allows user to change the width of …

Spectrogram UX improvements

---

Windows/MainWindow.UIControls.cs

This change allows to use `Ctrl` + `MouseWheel` to change the grid of the last BpmChange depending on the mouse position:

Change "Beat Division" depending on mouse position

---

Classes/Helper.cs
Classes/MapConverters/StepManiaMapConverter.cs
Windows/MainWindow.UIControls.cs
Windows/SongPreviewWindow.xaml.cs

#48 
Refactored Helper.FFmpeg to avoid running into issues when accessing or deleting the temporary file.
Tested with multiple Edda instances generating song previews at the same time and didn't run into any issues.

ffmpeg-temp.exe should not be deleted once created, instead it should be overwritten or left alone

---

Classes/Helper.cs
Classes/MapConverters/StepManiaMapConverter.cs
Windows/MainWindow.xaml.cs

#50 Fixed an issue that blocked users from replacing existing cover imageon maps after the recent changes to the cover filename convention.

Bug: Edda will not attempt to change cover image when the cover image is already set

---

Classes/Audio/AudioScanner.cs
Classes/Audio/DeviceChangeListener.cs
Classes/Audio/NoteScanner.cs
Classes/Audio/ParallelAudioPlayer.cs
Classes/Audio/VorbisSpectrogramGenerator.cs
Classes/Audio/VorbisWaveformGenerator.cs
Classes/EddaConstants.cs
Classes/MapEditor/MapEditor.cs
Classes/UI/EditorGridController.cs
Windows/MainWindow.GridControls.cs
Windows/MainWindow.UIControls.cs
Windows/MainWindow.xaml.cs

#46 Issue was caused by hanging autosave timer thread and map file references not being properly disposed of when closing the window.
Summary of the changes:
- Disposing of all the object references in MainWindow to avoid memory leaks and hanging threads when closing it.
- Implemented some guard rails for spectrogram generation, since it was being started multiple times when map was first being opened.
- Fixed an unusually large memory leaks caused by spectrogram generation trying to process too large BMPs.
Now the memory is manageable even for very large maps and is being (more or less) correctly released when closing a map and opening a different one.

Potential data corruption/deletion bug while creating new difficulty

---

Classes/Helper.cs
Classes/Integrations/DiscordClient.cs
Classes/MapEditor/BPMChange.cs
Classes/MapEditor/Bookmark.cs
Classes/MapEditor/EditManager/EditList.cs
Classes/MapEditor/MapEditor.cs
Classes/MapEditor/Note/Note.cs
Classes/UI/EditorGridController.cs
Windows/ChangeBPMWindow.xaml.cs
Windows/DifficultyPredictorWindow.xaml.cs
Windows/MainWindow.GridControls.cs
Windows/MainWindow.UIControls.cs
Windows/MainWindow.xaml.cs

#57 Implemented selection toggle of all the notes in specific bookmark/timing change on Ctrl+LeftClick.
To streamline certain operations, refactored MapDifficulty to store all notes, bookmarks and timing changes as SortedSet instead of List.
Implemented more frequent updates to the Discord Presence to better reflect the current status of user.

Selecting all the notes in a bookmark/timing change

---

App.xaml.cs

#66
Fixed an issue with Check Update dialog blocking main application window startup.

Bug: Old versions do not exit, leaves a thread with no purpose

---

Classes/Helper.cs
Windows/MainWindow.xaml.cs

#72
Implemented square check for cover images. It's not mandatory, but there's a popup informing user that the selected image will not be displayed in-game with an option to crop it automatically.

Force cover image to be a square

---

Windows/MainWindow.xaml.cs

#92 
Added a check for whether preferred output device is available at the time of running Edda.

Edda crashes if the selected audio device is not plugged in

---

Classes/EddaConstants.cs
Classes/MapEditor/Stats/MapStats.cs
Windows/MainWindow.xaml
Windows/MainWindow.xaml.cs

#91
Added stats indicator for Triple/Quadruple notes on a row.

Include info about Triple and Quadruple notes on a line

---

Classes/EddaConstants.cs

Release notes for 1.2.4:
* Include info about Triple and Quadruple notes on a line by @Brollyy in https://github.com/PKBeam/Edda/pull/97
* Implement scroll wheel hold by @Brollyy in https://github.com/PKBeam/Edda/pull/103
* Fixed a crash if the selected audio device is not plugged in by @Brollyy in https://github.com/PKBeam/Edda/pull/95
* Fixed a crash when trying to select a file `cover.jpg` for the map cover by @Brollyy in https://github.com/PKBeam/Edda/pull/96
**Note**: Edda is now using .NET 8.0. You need to download the [.NET 8.0 Runtime](https://dotnet.microsoft.com/download/dotnet/8.0/runtime) if you plan on using the `NoRuntime` executable.
Edda is now released under a [GPL-3.0 license](https://github.com/PKBeam/Edda?tab=GPL-3.0-1-ov-file#GPL-3.0-1-ov-file)
Once this version bump …

Bump the version to 1.2.4

---

Classes/Helper.cs
Classes/MapConverters/StepManiaMapConverter.cs

#113 #90 
Fixed several issues in Stepmania converter:
1. If there was no map author information, Edda refused to import the simfile instead of defaulting to empty Mapper field.
2. When there was a positive song offset and only one BPM change in the simfile, no notes were imported.
3. Simfiles that used MP3 song format were failing to import with very confusing error message - added an attempt to convert the MP3 into OGG Vorbis to at least try to handle this use case.

Error while importing SM map into Edda

---

Classes/MapEditor/RagnarockMap.cs

#112 Adjusted validation for the map data to allow maps that use a different _lineLayer than the default one.

_lineLayer is not a required value for official maps

---

Classes/EddaConstants.cs

Release notes for 1.2.5:
* Implemented a new, more accurate Difficulty Predictor model trained on OST and RAID songs. by @Nytilde, @Brollyy in https://github.com/PKBeam/Edda/pull/110
* Fixed the issue with incorrect format after trimming the cover image. by @Brollyy in https://github.com/PKBeam/Edda/pull/107
* Fixed an issue where maps saved by in-game editor couldn't be re-opened in Edda. by @Brollyy in https://github.com/PKBeam/Edda/pull/108
* Error while importing SM map into Edda by @Brollyy in https://github.com/PKBeam/Edda/pull/115
* Cannot import SM map that's using MP3 audio file. by @Brollyy in https://github.com/PKBeam/Edda/pull/115
* _lineLayer is not a required value for official maps by @Brollyy in https://github.com/PKBeam/Edda/pull/114
Release draft available at …

Release 1.2.5 version bump

---

Classes/Helper.cs

Fixed incorrect symbols for 1/6th and 5/6th runes.

---

Classes/MapEditor/MapEditor.cs

#118 
Added map stats recalculation when deleting lower (e.g. Easy) difficulty to reflect the stats of the map that becomes the new Easy difficulty immediately.

Song stats don't refresh after deleting difficulty

---

Classes/EddaConstants.cs
Classes/MapEditor/Stats/DifficultyPredictorNytilde.cs

* Due to many reports of instability in the new Difficulty Predictor, you can now choose between the old ML model created by @PKBeam (default), the new ML model created by @Nytilde (marked as beta for now), or a new algorithm based on distances between runes suggested by Melchior. by @Brollyy, @Nytilde, Melchior in #129
* Added an option to display the Difficulty Prediction for current map next to Map Stats, in real-time. by @Brollyy in https://github.com/PKBeam/Edda/pull/124
* Fixed incorrect symbols for 1/6th and 5/6th runes. by @Brollyy in https://github.com/PKBeam/Edda/pull/122
* Song stats don't refresh after deleting difficulty by @Brollyy in https://github.com/PKBeam/Edda/pull/123
* Error while importing SM map into Edda by @Brollyy in https://github.com/PKBeam/Edda/pull/117
* …

Release 1.2.6

---

Classes/Audio/AudioScanner.cs
Classes/Audio/BeatScanner.cs
Classes/Audio/NoteScanner.cs
Classes/EddaConstants.cs
Classes/Helper.cs
Classes/MapConverters/StepManiaMapConverter.cs
Classes/MapEditor/BPMChange.cs
Classes/MapEditor/MapEditor.cs
Classes/MapEditor/Note/Note.cs
Classes/MapEditor/Note/NoteSelection.cs
Classes/MapEditor/RagnarockMap.cs
Classes/MapEditor/Stats/DifficultyPredictorMelchior.cs
Classes/MapEditor/Stats/DifficultyPredictorNytilde.cs
Classes/MapEditor/Stats/DifficultyPredictorPKBeam.cs
Classes/MapEditor/Stats/MapStats.cs
Classes/UI/EditorGridController.cs
RagnarockEditor.csproj
Windows/ChangeBPMWindow.xaml.cs
Windows/MainWindow.UIControls.cs
Windows/MainWindow.xaml.cs
Windows/SettingsWindow.xaml
Windows/SettingsWindow.xaml.cs

#133 
I'm very sorry for a large PR - while working on the clipboard, I've also noticed several performance issues and smaller bugs with rune images sometimes showing X wrongly, so I've ended up going a bit too far and fixing them here as well.
1. Implemented native clipboard support for copying and pasting notes, using open source [RagnaRuneString library](https://github.com/Brollyy/RagnaRuneString) by @Brollyy to enable clipboard support outside Edda as well.
2. Implemented three different options when pasting notes, allowing mappers to select how they want the notes to be pasted, depending on source/target BPM.
3. Significantly improved performance of editor actions:
- highlighting and unhighlightning notes in large bulks
- highlighting all notes (Ctrl+A) and unhighlightning all notes …

Improve clipboard support

---

Classes/Audio/ParallelAudioPlayer.cs
Windows/MainWindow.xaml.cs

Implemented better error handling when Edda is started from incorrect working directory or resource files are missing.

Edda crashes when it cannot find the drum samples

---

Classes/MapEditor/RagnarockMap.cs

#143 
Removed required validation on beatmap version, as Ragnarock doesn't require it, and some maps on RC don't have it.

Improve handling of missing _version in beatmap files

---

Classes/Audio/BeatScanner.cs
Classes/Audio/NoteScanner.cs
Windows/MainWindow.xaml.cs

#145 
Fixed an issue with the note scanner and beat scanner resetting tempo after changing difficulty.

Beats don't match the song speed after changing difficulty

---

Classes/Audio/VorbisSpectrogramGenerator.cs
Classes/UI/EditorGridController.cs

#149 
This one was a doozy to debug... After multiple tests I finally narrowed the problem down to the way chunks are created using GDI.
The dynamic container height realignment makes the image jump a few pixels, but afterwards it aligns closer to the beat.

Spectrogram sometimes doesn't align correctly

---

Classes/UI/EditorGridController.cs
Windows/MainWindow.xaml
Windows/MainWindow.xaml.cs

#151 
Fixed an issue with waveform being rendered on top of the runes in some cases by giving it a separate Canvas.

Waveform renders on top of the runes after starting Edda

---

Classes/Helper.cs
Windows/MainWindow.xaml.cs

#150 
Implemented a failsafe in case there's an access issue on Edda-managed map files, e.g. due to OneDrive blocking the access due to ongoing sync.
EDIT: ignore the name of the branch, I goofed up

OneDrive causes crashes when saving

---

Classes/Audio/VorbisWaveformGenerator.cs
Classes/EddaConstants.cs
Classes/MapEditor/MapEditor.cs
Classes/UI/EditorGridController.cs
RagnarockEditor.csproj
Windows/CustomizeNavBarWindow.xaml
Windows/CustomizeNavBarWindow.xaml.cs
Windows/MainWindow.GridControls.cs
Windows/MainWindow.UIControls.cs
Windows/MainWindow.xaml
Windows/MainWindow.xaml.cs

#82 
Implemented visual indicators for placed notes and timing changes on the navigational waveform:
Since the navigation bar can get crowded, there's also a new button in the right panel that opens a window for customizing what shows up there and what colors are used:

Display notes on navigational waveform

---

Classes/EddaConstants.cs

* Display notes on navigational waveform by @Brollyy in https://github.com/PKBeam/Edda/pull/148
* Beats don't match the song speed after changing difficulty by @Brollyy in https://github.com/PKBeam/Edda/pull/147
* Spectrogram sometimes doesn't align correctly by @Brollyy in https://github.com/PKBeam/Edda/pull/156
* Waveform renders on top of the runes after starting Edda by @Brollyy in https://github.com/PKBeam/Edda/pull/153
* OneDrive causes crashes when saving by @Brollyy in https://github.com/PKBeam/Edda/pull/152
* Fixed an issue with incorrect BPM values imported from SSC files. by @Brollyy in https://github.com/PKBeam/Edda/pull/155
For the list of the other features and bugfixes introduced in 1.2.7 compared to 1.2.6, please check release notes for [1.2.7 Beta …

Bump version to 1.2.7
