EddaConstants.cs

Tested "Hellfest" for possible environment value and works fine. Possibly needs a test to check, if users missing the dlc can play/see the env properly or if the game reverts to default fog if the env can not be found in the game files.

Inserted Hellfest DLC Environment

---

Classes/Helper.cs

Fixed issue whereby new users could not start a new map as they don't have a usersetting file yet.

Failed to read from usersetting

---

.gitignore
Classes/MapConverters/IMapConverter.cs
Classes/MapConverters/StepManiaMapConverter.cs
Classes/MapConverters/StepManiaUtils/ChartMetadataExtra.cs
Classes/MapConverters/StepManiaUtils/SmFileExtra.cs
Classes/MapConverters/StepManiaUtils/StepMetadataExtra.cs
README.md
RagnarockEditor.csproj
Windows/MainWindow.MenuItems.cs
Windows/MainWindow.xaml
Windows/MainWindow.xaml.cs
Windows/StartWindow.xaml
Windows/StartWindow.xaml.cs

https://github.com/PKBeam/Edda/issues/8

Implemented import from .sm and .ssc simfiles into Edda.

---

Classes/MapEditor/MapEditor.cs

Notes couldn't be copied over between difficulties anymore, which works fine on 1.1.0.

Fixed a regression introduced during refactor

---

Classes/MapEditor/MapEditor.cs
Windows/MainWindow.MenuItems.cs
Windows/MainWindow.UIControls.cs
Windows/MainWindow.xaml
Windows/MainWindow.xaml.cs

https://en.wikipedia.org/wiki/Quantization_(music)

new featuere to enable quantization of the selected section

---

Classes/MapEditor/MapEditor.cs

i assumed that the `grid` was data related to time. but it is its own scaling. I have adjusted my calculations accordingly and tested it with 10 different time changes, and all of them have landed exactly in the right place.

fixed calculation

---

Classes/EddaConstants.cs
Classes/MapEditor/RagnarockMap.cs
Windows/MainWindow.UIControls.cs
Windows/MainWindow.xaml.cs

Changed the way button for selected difficulty is displayed to make it clearer which map is being currently worked on.

Difficulty button accessibility

---

Classes/EddaConstants.cs

New DLC enironment name confirmed with emokee.

Added new Sabaton DLC and missing Empty environment options.

---

Classes/EddaConstants.cs

**Bugfixes:**
- Fixed a regression with difficulty buttons not being accessible after playing and pausing a song.
- Fixed an issue that blocked users from replacing existing cover image on maps after the recent changes to the cover filename convention.
#50
- Refactored Helper.FFmpeg to avoid running into issues when accessing or deleting the temporary file.
#48
- Fixed issues with memory leaks and map files being overwritten after map was closed already.
#46
#16
**Draft release with publish packages is prepared already (https://github.com/PKBeam/Edda/releases/edit/untagged-2ba5c311043e45d583fb) - after merging this PR, it can be published.**

Increment version number for 1.2.1 release.

---

Classes/Audio/AudioScanner.cs
Classes/Audio/DeviceChangeListener.cs
Classes/UI/EditorGridController.cs
Windows/MainWindow.MenuItems.cs
Windows/MainWindow.UIControls.cs
Windows/MainWindow.xaml.cs
Windows/SettingsWindow.xaml.cs

#63 Added guardrails that ensure Edda is still functioning properly even when there are no audio devices.

Edda shuts down when no audio devices are connected

---

Classes/UI/EditorGridController.cs
Windows/ChangeBPMWindow.xaml.cs
Windows/MainWindow.MenuItems.cs
Windows/MainWindow.UIControls.cs
Windows/MainWindow.xaml.cs
Windows/SettingsWindow.xaml.cs
Windows/SongPreviewWindow.xaml.cs
Windows/StartWindow.xaml.cs

#67 
Assigned all Message Boxes to their originating window to avoid layering issues.

Bug: Song preview generation window has incorrect modality

---

.github/workflows/code-quality.yml

Discussed on #65 to make sure we can keep the formatting consistent going forward.

Added Github Action for checking code formatting on pull requests.

---

Classes/Audio/VorbisSpectrogramGenerator.cs
Classes/Helper.cs
Classes/MapEditor/MapEditor.cs
Classes/MapEditor/Stats/MapStats.cs
Classes/UI/EditorGridController.cs
Windows/DifficultyPredictorWindow.xaml.cs
Windows/MainWindow.xaml
Windows/MainWindow.xaml.cs

Implemented some live map stats tracking.
I've elected to drop CPU usage and Effective BPM, sincethey don't quite fit into UI on window mode and I'm not sure they'd deliver that much value over what's been done. Adding them later shouldn't be an issue, although CPU usage is not really a map statistic, so I don't think it should be in that section to begin with.

Implemented some live map stats tracking.

---

Classes/EddaConstants.cs
Windows/MainWindow.UIControls.cs
Windows/MainWindow.xaml
Windows/MainWindow.xaml.cs

#70
Increased max song tempo to x2.00, adjusted the jumps done with keyboard to be more granular and added a quick way to return to normal tempo by double-clicking the slider.

Playback rate improvement

---

Classes/EddaConstants.cs
Classes/UI/SongPreviewController.cs
Windows/MainWindow.UIControls.cs
Windows/MainWindow.xaml.cs

Fixed an issue with preview player causing a crash when changing device without any preview set.

Preview player crashes the application

---

RagnarockEditor.csproj
RagnarockEditor.sln

#94 
Upgraded Edda to .NET 8.0 with Upgrade Assistant.

Update to .NET 8.0

---

Windows/MainWindow.xaml.cs

#93 
Added additional checks for cover files to avoid crashes.

Edda crashes if cover file has wrong DPI

---

Classes/Helper.cs

Fixed the issue with incorrect format after trimming the cover image.

---

Classes/MapEditor/RagnarockMap.cs

Fixed an issue where maps saved by in-game editor couldn't be re-opened in Edda.

---

Classes/MapConverters/StepManiaMapConverter.cs

#113 
Further fixes to the SM note converter after the closed issue was reported still not fixed.

Error while importing SM map into Edda

---

Windows/MainWindow.xaml.cs

#126 
Changed Export Map logic to only export relevant files to the ZIP.

Export Map included too many files

---

Classes/EddaConstants.cs
Classes/MapEditor/RagnarockMap.cs
Windows/MainWindow.xaml.cs
Windows/SettingsWindow.xaml
Windows/SettingsWindow.xaml.cs

Grid Spacing should be saved
